New pull request as per requests from live-lab team for CW24 HOL
oracle-livelabs/oracle-health pull request #10
Opened 2024-08-30 21:01 UTC by rghosh9

Require a new PR for emergency PR submission for CW24 as per requests from live-lab team
Also, all minor formatting issues are resolved and live-lab retested by the Oracle Health team

Old PR here - https://github.com/oracle-livelabs/oracle-health/pull/7/files

2024-09-02 06:30 UTC, ramonamagadan18 commented on compliance-form-generation-with-OCI-GenAI/other-livelabs/other-livelabs.md
Hi @rghosh9 Please use the URLs from the new web domain: the LiveLabs webpage to now start with livelabs.oracle.com . For example for your first link will be: https://livelabs.oracle.com/pls/apex/f?p=133:180:115467694451312::::wid:3762

2024-09-02 06:32 UTC, ramonamagadan18 commented on compliance-form-generation-with-OCI-GenAI/workshops/tenancy/manifest.json
Hi @rghosh9 ! Please use one single format for your labs: you had used "Lab 1"; "Lab2" etc ; which is perfect but now you have "Lab-3", which is not a LiveLabs format.

2024-09-02 06:34 UTC, ramonamagadan18 requested changes
Hi @rghosh9 Please add your WMS ID and see my other comments. Also, you have conflicts that must be solved.

2024-09-03 08:36 UTC, klazarz commented
@rghosh9 please resolve conflicts

2024-09-03 14:08 UTC, rghosh9 commented on compliance-form-generation-with-OCI-GenAI/workshops/tenancy/manifest.json
Thank you. Fixed all with a single format.

2024-09-03 14:10 UTC, rghosh9 commented
> Hi @rghosh9 Please add your WMS ID and see my other comments. Also, you have conflicts that must be solved.

WMS IS 11685

2024-09-03 14:21 UTC, rghosh9 commented
Need help on resolving these conflicts? Not sure. Any insights you can share?

2024-09-03 15:24 UTC, closed without merging