WMS ID #11685 recreate the folder
oracle-livelabs/oracle-health pull request #11
Opened 2024-09-03 15:55 UTC by rghosh9

2024-09-03 16:50 UTC, klazarz requested changes
@rghosh9 please update developer.oracle.com/livelabs in index.html to livelabs.oracle.com

2024-09-03 17:47 UTC, rghosh9 commented
Working with @anacoman11 and @ramonamagadan18 on this. The index already has this (below) - Let me know if I need to update any other place. Thanks in advance..
<body>
    <header class="hol-Header" role="banner">
        <div class="hol-Header-wrap">
            <div class="hol-Header-logo"><span>Oracle LiveLabs</span></div>
            <a href="https://developer.oracle.com/livelabs" target="_blank" id="livelabs" title="Oracle LiveLabs"></a>
            <div class="hol-Header-actions">
                <button id="openNav" class="hol-Header-button hol-Header-button--menu rightNav" aria-label="Open Menu"
                    title="Open Menu">
                    <span class="hol-Header-toggleIcon"></span>
                </button>
            </div>
        </div>
    </header>

2024-09-03 20:49 UTC, rghosh9 commented
Thanks @klazarz - I have made the changes to livelabs.oracle.com and syncd up

2024-09-04 05:55 UTC, klazarz approved these changes

2024-09-04 05:55 UTC, merged