Build a SMART on FHIR Application with Oracle Autonomous Cloud Services
oracle-livelabs/oracle-health pull request #2
Opened 2023-08-17 13:56 UTC by AlexandruBasarab

Add here your WMS ID - 11459

General requirements

    Information in the workshop is adequate and updated
    Code is correct and working
    Links are correct
    Make sure you enter the help email link in your manifest.json
    Please make sure WMS URLs are updated as needed after your PR is approved

Checklist - Refer to the QA document for the complete list

Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2023-08-17 15:39 UTC, anooshapilli commented on smart-on-fhir/0-introduction/introduction.md
> +## Workshop Overview
@AlexandruBasarab - Update to About this Workshop

2023-08-17 15:39 UTC, anooshapilli commented on smart-on-fhir/0-introduction/introduction.md
> +Estimated Time: 2 hours
@AlexandruBasarab - Rename to Estimated Workshop Time

2023-08-17 15:42 UTC, anooshapilli reviewed
@AlexandruBasarab - Please make the requested changes to the workshop.
- Remove the .ds_store files 
<img width="301" alt="image" src="https://github.com/oracle-livelabs/oracle-health/assets/63126232/63de55a3-b1c9-4b9d-865d-12e03ab6483f">

2023-08-17 15:42 UTC, anooshapilli commented on smart-on-fhir/0-introduction/introduction.md
> +## Learn More - Useful Links
@AlexandruBasarab - Remove - useful links

2023-08-17 15:42 UTC, anooshapilli commented on smart-on-fhir/0-introduction/introduction.md
> +### During this workshop, we will cover the following steps:
@AlexandruBasarab - Please add Objectives and Prerequisites

2023-08-17 17:11 UTC, ramumg commented on smart-on-fhir/0-introduction/files/ascvd-risk.min.js
![image](https://github.com/oracle-livelabs/oracle-health/assets/84869754/d34b1176-58b7-491a-bae2-0d5920a919ab)
Please follow these steps for this file.

2023-08-17 17:11 UTC, ramumg commented on smart-on-fhir/0-introduction/files/ascvd-risk.sql
![image](https://github.com/oracle-livelabs/oracle-health/assets/84869754/3764e655-4fde-4a27-a43d-a3cb4e8c4a69)
Please follow these steps for this file.

2023-08-17 17:11 UTC, ramumg commented on smart-on-fhir/0-introduction/files/fhir-client.min.js
![image](https://github.com/oracle-livelabs/oracle-health/assets/84869754/3764e655-4fde-4a27-a43d-a3cb4e8c4a69)
Please follow these steps for this file.

2023-08-17 17:12 UTC, ramumg commented on smart-on-fhir/0-introduction/introduction.md
> +Estimated Time: 2 hours
@AlexandruBasarab, I still see it as Estimated Time instead of Workshop Time

2023-08-17 17:13 UTC, ramumg requested changes
@AlexandruBasarab  Please make the necessary changes that were commented so we can approve this PR.

Thank you!

2023-08-18 14:09 UTC, denisemyrick approved these changes

2023-08-18 16:30 UTC, merged